apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  labels:
    cloud: vSphere
    cluster.open-cluster-management.io/clusterset: default
    vendor: OpenShift
  name: cluster-name
  namespace: cluster-name
spec:
  baseDomain: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "baseDomain") | base64dec }}'
  clusterName: cluster-name
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    vsphere:
      certificatesSecretRef:
        name: vsphere-cert
      cluster: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "cluster") | base64dec }}'
      credentialsSecretRef:
        name: vsphere-creds
      datacenter: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "datacenter") | base64dec }}'
      defaultDatastore: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "defaultDatastore") | base64dec }}'
      folder: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "vsphereFolder") | base64dec }}'
      network: xxx
      vCenter: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "vCenter") | base64dec }}'
  provisioning:
    imageSetRef:
      name: img4.12.6-multi-appsub
    installConfigSecretRef:
      name: install-config
    sshPrivateKeySecretRef:
      name: ssh-privatekey
  pullSecretRef:
    name: rh-pull-secret
