apiVersion: v1
kind: Secret
metadata:
  name: rh-pull-secret
  namespace: cluster-name
data:
  .dockerconfigjson: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "pullSecret") }}'
type: kubernetes.io/dockerconfigjson
