apiVersion: v1
kind: Secret
metadata:
  name: vsphere-certs
  namespace: cluster-name
data:
  .cacert: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "cacertificate") | base64encode  }}'
type: Opaque
