apiVersion: v1
kind: Secret
metadata:
  name: vsphere-creds
  namespace: cluster-name
data:
  username: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "username") | base64encode  }}'
  password: '{{ (fromSecret "cluster-provider-infra" "vsphere-creds" "password") | base64encode  }}'
type: Opaque
