apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: worker-machinepool
spec:
  platform:
    vsphere:
      coresPerSocket: 2
      cpus: 4
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120