apiVersion: v1
kind: Secret
metadata:
  name: aws-certs
  namespace: cluster-name
data:
  .cacert: '{{ (fromSecret "cluster-provider-infra" "aws-creds" "cacertificate") | base64encode  }}'
type: Opaque
