apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: cluster-name
data:
  aws_access_key_id: '{{ (fromSecret "cluster-provider-infra" "aws-creds" "aws_access_key_id") }}'
  aws_secret_access_key: '{{ (fromSecret "cluster-provider-infra" "aws-creds" "aws_secret_access_key") }}'
type: Opaque
