apiVersion: v1
kind: Secret
metadata:
  name: ssh-privatekey
  namespace: cluster-name
data:
  ssh-privatekey: '{{ (fromSecret "cluster-provider-infra" "aws-creds" "ssh-privatekey") | base64encode  }}'
type: Opaque
