apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: worker-machinepool
spec:
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 120
        type: io1
      type: m5.xlarge
