apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: cluster-name
  namespace: cluster-name
spec:
  applicationManager:
    enabled: true
    proxyPolicy: OCPGlobalProxy
  certPolicyController:
    enabled: true
    proxyPolicy: OCPGlobalProxy
  clusterName: cluster-name
  clusterNamespace: cluster-name
  clusterLabels:
    vendor: OpenShift
  iamPolicyController:
    enabled: true
    proxyPolicy: OCPGlobalProxy
  policyController:
    enabled: true
    proxyPolicy: OCPGlobalProxy
  searchCollector:
    enabled: true
    proxyPolicy: OCPGlobalProxy
