apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  ## configure kustomize to correct the name of the Policy namespace in the Policy dependency
  - ./kustomize-configs/namespace-namereference.yml
  
## include all files that should be included as part of the base objects
resources:
  - namespace.yml
  - klusterletaddonconfig.yml
  - managedcluster.yml
  - worker-machinepool.yml

